# Generated by Django 5.2 on 2025-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_account',
            field=models.FileField(blank=True, max_length=20, null=True, upload_to='', verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_bik',
            field=models.FileField(blank=True, max_length=9, null=True, upload_to='', verbose_name='БИК'),
        ),
    ]
