# Generated by Django 5.2.3 on 2025-07-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cartitem_cart_remove_deliveryaddress_company_and_more'),
        ('main', '0007_invoice_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_link', to='main.invoice'),
        ),
    ]
