# Generated by Django 5.2.3 on 2025-07-10 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_company_inn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обращение в поддержку', 'verbose_name_plural': 'Обращения в поддержку'},
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='resolved',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для связи'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('resolved', 'Решен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_type',
            field=models.CharField(choices=[('general', 'Общий вопрос'), ('legal', 'Юридический'), ('payment', 'Оплата'), ('technical', 'Технический')], max_length=20, verbose_name='Тип обращения'),
        ),
    ]
