# Generated by Django 5.2.3 on 2025-06-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlproduct',
            name='attachments_local',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='big_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='products/big/'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='small_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='products/small/'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='super_big_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='products/super_big/'),
        ),
    ]
