# Generated by Django 5.2.3 on 2025-07-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlproduct',
            name='application_type',
            field=models.CharField(blank=True, choices=[('uv_print', 'УФ-печать'), ('laser_engraving', 'Лазерная гравировка'), ('embroidery', 'Вышивка'), ('silk_print', 'Шелкография'), ('tampo_print', 'Тамопечать'), ('thermal_print', 'Термопечать')], max_length=100, verbose_name='Вид нанесения'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='ball_diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Диаметр шарика'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='block_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет блока'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='block_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер блока'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='box_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер коробки/полотна'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='calendar_grid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Календарная сетка'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='collection',
            field=models.CharField(blank=True, max_length=100, verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='cover_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал обложки'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='cover_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип обложки'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='cut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Крой'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='dating',
            field=models.CharField(blank=True, max_length=100, verbose_name='Датировка'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='density',
            field=models.CharField(blank=True, max_length=50, verbose_name='Плотность (г/м²)'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='edge_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Обрез блока'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='fit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посадка'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='for_kids',
            field=models.BooleanField(default=False, verbose_name='Для детей'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='format_size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужские'), ('female', 'Женские'), ('unisex', 'Унисекс')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='has_lining',
            field=models.BooleanField(default=False, verbose_name='Есть подкладка'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='individual_packaging',
            field=models.BooleanField(default=False, verbose_name='Индивидуальная упаковка'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='is_eco',
            field=models.BooleanField(default=False, verbose_name='Эко-подарки'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='is_profitable',
            field=models.BooleanField(default=False, verbose_name='Выгодно'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='lining',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Изнанка'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='made_in_russia',
            field=models.BooleanField(default=False, verbose_name='Сделано в России'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='marking_type',
            field=models.CharField(blank=True, choices=[('textile', 'Текстиль'), ('other', 'Другое')], max_length=20, verbose_name='Тип маркировки'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='mechanism_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Механизм'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('bag', 'Пакет'), ('gift_box', 'Подарочная коробка'), ('none', 'Без упаковки')], max_length=20, verbose_name='Тип упаковки'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число страниц'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='pantone_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Пантон (цвет)'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='refill_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип стержня'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='replaceable_refill',
            field=models.BooleanField(default=False, verbose_name='Сменный стержень'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='requires_marking',
            field=models.BooleanField(default=False, verbose_name='Подлежит маркировке'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='ribbon_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет ляссе'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='special_filters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='stock_marking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='umbrella_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип зонта'),
        ),
        migrations.AddField(
            model_name='xmlproduct',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
