# Generated by Django 5.2.3 on 2025-07-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_xmlproduct_application_type_xmlproduct_ball_diameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('products', models.ManyToManyField(related_name='application_types', to='main.xmlproduct')),
            ],
            options={
                'verbose_name': 'Тип нанесения',
                'verbose_name_plural': 'Типы нанесения',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.xmlproduct')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=50)),
                ('filter_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('products', models.ManyToManyField(related_name='product_filters', to='main.xmlproduct')),
            ],
            options={
                'verbose_name': 'Фильтр товара',
                'verbose_name_plural': 'Фильтры товаров',
                'unique_together': {('filter_type', 'filter_id')},
            },
        ),
    ]
