# Generated by Django 5.2.3 on 2025-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_invoice_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='printing_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Метод нанесения'),
        ),
    ]
