# Generated by Django 5.2.3 on 2025-07-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orderitem_printing_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='printing_method',
        ),
    ]
