# Generated by Django 5.2.3 on 2025-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_orderitem_printing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_sizes',
            field=models.JSONField(blank=True, default=dict, help_text="Словарь с размерами и их количеством в формате {'size': quantity}", verbose_name='Выбранные размеры'),
        ),
    ]
