# Generated by Django 5.2.3 on 2025-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_gender_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlproduct',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужские'), ('female', 'Женские'), ('unisex', 'Унисекс')], max_length=10, verbose_name='Пол'),
        ),
    ]
