# Generated by Django 5.2.3 on 2025-08-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_usercustomdesign_product_and_more'),
        ('main', '0014_alter_xmlproduct_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='designer.customproductorder', verbose_name='Кастомный товар'),
        ),
    ]
