# Generated by Django 5.2.3 on 2025-08-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_alter_customproductorder_selected_color'),
        ('main', '0015_orderitem_custom_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='custom_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.customproductorder', verbose_name='Кастомный товар'),
        ),
    ]
