# Generated by Django 5.2.3 on 2025-07-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_remove_orderitem_printing_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('front_image', models.ImageField(upload_to='design_templates/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='design_templates/back/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='main.xmlproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DesignArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('max_text_length', models.IntegerField(default=50)),
                ('allow_images', models.BooleanField(default=True)),
                ('allow_text', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_areas', to='designer.designtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
                ('preview_image', models.ImageField(upload_to='product_colors/')),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_colors', to='main.xmlproduct')),
            ],
        ),
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.xmlproduct')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.designtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DesignOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.productcolor')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.userdesign')),
            ],
        ),
        migrations.CreateModel(
            name='DesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_designs/')),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('font_size', models.IntegerField(default=14)),
                ('rotation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.designarea')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='designer.userdesign')),
            ],
        ),
    ]
