# Generated by Django 5.2.3 on 2025-07-20 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
                ('preview_image', models.ImageField(upload_to='product_colors/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XXS', 'XXS (40-42)'), ('XS', 'XS (44-46)'), ('S', 'S (48)'), ('M', 'M (50)'), ('L', 'L (52)'), ('XL', 'XL (54)'), ('XXL', 'XXL (56-58)'), ('3XL', '3XL (60-62)'), ('4XL', '4XL (64-66)'), ('5XL', '5XL (68-70)'), ('6XL', '6XL (72-74)'), ('7XL', '7XL (76-78)')], max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='designelement',
            name='area',
        ),
        migrations.RemoveField(
            model_name='designelement',
            name='design',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='design',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='selected_color',
        ),
        migrations.RemoveField(
            model_name='designtemplate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userdesign',
            name='template',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userdesign',
            name='product',
        ),
        migrations.CreateModel(
            name='CustomProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sizes', models.ManyToManyField(related_name='templates', to='designer.customproductsize')),
            ],
        ),
        migrations.CreateModel(
            name='CustomProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='custom_products/')),
                ('is_front', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designer.customproducttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomDesignArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('max_text_length', models.IntegerField(default=50)),
                ('allow_images', models.BooleanField(default=True)),
                ('allow_text', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_areas', to='designer.customproducttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.customproducttemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designer.customproductcolor')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.usercustomdesign')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDesignElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_custom_designs/')),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('font_size', models.IntegerField(default=14)),
                ('rotation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.customdesignarea')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='designer.usercustomdesign')),
            ],
        ),
        migrations.DeleteModel(
            name='DesignArea',
        ),
        migrations.DeleteModel(
            name='DesignElement',
        ),
        migrations.DeleteModel(
            name='DesignOrder',
        ),
        migrations.DeleteModel(
            name='DesignTemplate',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='UserDesign',
        ),
    ]
