# Generated by Django 5.2.3 on 2025-08-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductorder',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
