# Generated by Django 5.2.3 on 2025-08-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_customproductorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductorder',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
    ]
