# Generated by Django 5.2.3 on 2025-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_customproductcolor_customproductsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductimage',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customproductimage',
            name='is_front',
            field=models.BooleanField(default=False),
        ),
    ]
