# Generated by Django 5.2.3 on 2025-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_customproductimage_is_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesignelement',
            name='side',
            field=models.CharField(choices=[('front', 'Лицевая сторона'), ('back', 'Тыльная сторона')], default='front', max_length=10),
        ),
    ]
