# Generated by Django 5.2.3 on 2025-08-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_customproductorder_in_cart'),
        ('main', '0010_cartitem_selected_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductorder',
            name='original_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.xmlproduct', verbose_name='Оригинальный товар'),
        ),
    ]
