# Generated by Django 5.2.3 on 2025-08-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_customproductorder_original_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdesignelement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='design_elements/'),
        ),
    ]
