# Generated by Django 5.2.3 on 2025-07-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_customdesignelement_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductcolor',
            name='gradient_css',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customproductcolor',
            name='is_pattern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customproductcolor',
            name='pattern_image',
            field=models.ImageField(blank=True, null=True, upload_to='color_patterns/'),
        ),
        migrations.AlterField(
            model_name='customproductcolor',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_colors/'),
        ),
        migrations.CreateModel(
            name='ProductSilhouette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_image', models.ImageField(upload_to='product_silhouettes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette', to='designer.customproducttemplate')),
            ],
        ),
    ]
