# Generated by Django 5.2.3 on 2025-08-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_alter_customdesignelement_image'),
        ('main', '0010_cartitem_selected_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomdesign',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.xmlproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='usercustomdesign',
            unique_together={('user_session', 'product')},
        ),
    ]
