# Generated by Django 5.2.3 on 2025-07-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_customproductcolor_gradient_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mask_image', models.ImageField(upload_to='product_masks/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='designer.customproducttemplate')),
            ],
        ),
    ]
