# Generated by Django 5.2.3 on 2025-08-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_usercustomdesign_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproductorder',
            name='selected_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designer.customproductcolor'),
        ),
    ]
