# Generated by Django 5.2.3 on 2025-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_productmask'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsilhouette',
            name='colored_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
