# Generated by Django 5.2.3 on 2025-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_productsilhouette_colored_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproductimage',
            name='is_silhouette',
            field=models.BooleanField(default=False, verbose_name='Use as silhouette'),
        ),
    ]
