# Generated by Django 5.2.3 on 2025-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0008_customproductimage_is_silhouette'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsilhouette',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_silhouettes/'),
        ),
    ]
